version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: spotify-mcp
    main: ./cmd/mcp-server
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: linux
        format: zip
      - goos: darwin
        format: zip
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: dog0sd
    name: spotify-mcp
  draft: false
  prerelease: false
  name_template: 'v{{ .Version }}'
